/**
 * Demo Seeding — Pure data builders
 *
 * Builders for the sample data a fresh demo account ships with. They are
 * deliberately PURE (no DB) so they can be unit-tested in isolation. The API
 * route `app/api/demo/seed/route.ts` calls these builders and writes the
 * results to the DB.
 *
 * Naming convention: every demo job title contains "Demo" so a quick
 * `db.job.findMany({ where: { title: { contains: 'Demo' } } })` finds them for
 * dashboard filtering and Playwright assertions.
 *
 * Field names mirror the Prisma schema:
 *  - Job.employerId (FK to Employer.userId)
 *  - Job.type (JobType enum, UPPERCASE)
 *  - Job.category (JobCategory enum, UPPERCASE)
 *  - Job.status (JobStatus enum, lowercase: 'approved' for live listings)
 *  - Application.seekerId (FK to JobSeeker.userId)
 *  - Application.resumeUrl (required)
 */

import type { JobType, JobCategory, JobStatus, ApplicationStatus } from '@prisma/client'

/* -------------------------------------------------------------------------- */
/* Onboarding stubs — what we prefill into the onboarding form                */
/* -------------------------------------------------------------------------- */

export interface SeekerOnboardingStub {
  role: 'seeker'
  firstName: string
  lastName: string
  location: string
  experience: string
  skills: string[]
  professionalSummary: string
}

export interface EmployerOnboardingStub {
  role: 'employer'
  firstName: string
  lastName: string
  location: string
  companyName: string
  companySize: string
}

function firstNameFromDemoName(name: string): string {
  // e.g. "demo-seeker-1719938112443" → "Demo"
  return 'Demo'
}

function lastNameFromDemoName(name: string, role: string): string {
  // e.g. "demo-seeker-1719938112443" → "Seeker 1719938112443"
  const tail = name.replace(/^demo-/, '').replace(/^\w+-/, '')
  const titleCase = role.charAt(0).toUpperCase() + role.slice(1)
  return `${titleCase} ${tail}`.trim()
}

export function buildSeekerOnboardingStub({ name }: { name: string }): SeekerOnboardingStub {
  return {
    role: 'seeker',
    firstName: firstNameFromDemoName(name),
    lastName: lastNameFromDemoName(name, 'seeker'),
    location: 'Remote (US)',
    experience: '5',
    skills: ['JavaScript', 'TypeScript', 'React', 'Next.js', 'PostgreSQL'],
    professionalSummary:
      'Demo job seeker generated by the AmperTalent demo flow. This account can be used to test the seeker onboarding, profile, and application flow end-to-end.',
  }
}

export function buildEmployerOnboardingStub({ name }: { name: string }): EmployerOnboardingStub {
  return {
    role: 'employer',
    firstName: firstNameFromDemoName(name),
    lastName: lastNameFromDemoName(name, 'employer'),
    location: 'Remote (US)',
    companyName: 'Demo Co.',
    companySize: '11-50',
  }
}

/* -------------------------------------------------------------------------- */
/* Sample jobs                                                                */
/* -------------------------------------------------------------------------- */

interface SampleJobTemplate {
  title: string
  description: string
  locationText: string
  category: JobCategory
  type: JobType
}

const SAMPLE_JOB_TEMPLATES: SampleJobTemplate[] = [
  {
    title: 'Senior Demo Engineer (Remote)',
    description:
      'We are looking for a passionate engineer to join our distributed team. You will own features end-to-end, work closely with design, and ship to production weekly.',
    locationText: 'Remote (US)',
    category: 'PROGRAMMER',
    type: 'FULL_TIME',
  },
  {
    title: 'Demo Product Designer (Remote)',
    description:
      'Help shape the future of remote work at AmperTalent. You will design delightful experiences for job seekers and employers across web and mobile.',
    locationText: 'Remote (Worldwide)',
    category: 'DESIGN',
    type: 'FULL_TIME',
  },
  {
    title: 'Demo Customer Success Manager (Remote)',
    description:
      'Be the voice of our customers. You will partner with engineering and product to triage feedback and turn it into a roadmap.',
    locationText: 'Remote (Americas)',
    category: 'CUSTOMER_SERVICE',
    type: 'FULL_TIME',
  },
  {
    title: 'Demo Full-Stack Engineer (Remote)',
    description:
      'Own a slice of our stack from front-end to back-end. We use TypeScript, React, Next.js, and Postgres.',
    locationText: 'Remote (US)',
    category: 'PROGRAMMER',
    type: 'FULL_TIME',
  },
  {
    title: 'Demo Marketing Lead (Remote)',
    description:
      'Build and run our growth engine. You will experiment across paid, content, and lifecycle channels.',
    locationText: 'Remote (US)',
    category: 'MARKETING_PUBLIC_RELATIONS',
    type: 'PART_TIME',
  },
  {
    title: 'Demo Data Analyst (Remote)',
    description:
      'Turn raw data into clear narratives. You will partner with leadership to define the metrics that matter.',
    locationText: 'Remote (US)',
    category: 'CONSULTANT',
    type: 'PERMANENT',
  },
  {
    title: 'Demo QA Engineer (Remote)',
    description:
      'Keep our releases safe. You will design and run test plans, automate regressions, and partner with engineering on quality.',
    locationText: 'Remote (Worldwide)',
    category: 'COMPUTER_IT',
    type: 'TEMPORARY',
  },
  {
    title: 'Demo Technical Writer (Remote)',
    description:
      'Make complex topics simple. You will own our public docs, in-app copy, and developer guides.',
    locationText: 'Remote (US)',
    category: 'BLOGGER',
    type: 'PART_TIME',
  },
  {
    title: 'Demo DevOps Engineer (Remote)',
    description:
      'Run the platform. You will own our CI/CD, observability, and incident response.',
    locationText: 'Remote (US)',
    category: 'COMPUTER_IT',
    type: 'FULL_TIME',
  },
  {
    title: 'Demo Recruiter (Remote)',
    description:
      'Help us grow the team. You will run the full-cycle recruiting process for engineering roles.',
    locationText: 'Remote (US)',
    category: 'HUMAN_RESOURCES',
    type: 'FULL_TIME',
  },
]

export interface SampleJob {
  title: string
  description: string
  locationText: string
  category: JobCategory
  type: JobType
  status: JobStatus
  employerId: string
  skillsRequired: string[]
  payRangeText: string | null
}

export function buildSampleJobs({
  employerProfileId,
  count = 3,
}: {
  employerProfileId: string
  count?: number
}): SampleJob[] {
  const safeCount = Math.max(1, Math.min(count, SAMPLE_JOB_TEMPLATES.length))
  const out: SampleJob[] = []
  // Pick `safeCount` distinct templates so the same visitor gets fresh jobs each
  // time. We shuffle a copy of the templates array.
  const indices = Array.from({ length: SAMPLE_JOB_TEMPLATES.length }, (_, i) => i)
  for (let i = indices.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[indices[i], indices[j]] = [indices[j], indices[i]]
  }
  for (let i = 0; i < safeCount; i++) {
    const tpl = SAMPLE_JOB_TEMPLATES[indices[i]]
    out.push({
      title: tpl.title,
      description: tpl.description,
      locationText: tpl.locationText,
      category: tpl.category,
      type: tpl.type,
      status: 'approved',
      employerId: employerProfileId,
      skillsRequired: ['Communication', 'Remote Collaboration', 'TypeScript'],
      payRangeText: i === 0 ? '$90k - $130k' : i === 1 ? '$70k - $100k' : '$50k - $80k',
    })
  }
  return out
}

/* -------------------------------------------------------------------------- */
/* Sample applications                                                        */
/* -------------------------------------------------------------------------- */

export interface SampleApplication {
  seekerId: string
  jobId: string
  status: ApplicationStatus
  resumeUrl: string
  coverLetter: string | null
}

export function buildSampleApplications({
  seekerProfileId,
  jobs,
  max = 3,
}: {
  seekerProfileId: string
  jobs: Array<{ id: string; title?: string }>
  max?: number
}): SampleApplication[] {
  const capped = Math.min(max, jobs.length)
  return jobs.slice(0, capped).map((job, idx) => ({
    seekerId: seekerProfileId,
    jobId: job.id,
    status: 'pending' as ApplicationStatus,
    resumeUrl: `https://ampertalent-demo.com/resumes/${seekerProfileId}-${idx}.pdf`,
    coverLetter:
      idx === 0
        ? 'Hi! I saw the demo job posting and I am very interested. I have shipped similar features before and would love to chat.'
        : null,
  }))
}
