/**
 * AUTO-GENERATE ALL AVAILABLE FIELDS TEST
 * 
 * Tests that auto-generation creates mappings for ALL available GHL fields,
 * not just the hardcoded 10. This includes:
 * - All standard GHL fields (email, phone, name, etc.)
 * - All custom GHL fields in the location
 * 
 * TDD: Write test first, then update AutoGenerationService
 */

import { db } from "@/lib/db"
import { AutoGenerationService } from "@/lib/auto-generation-service"
import { GHLSyncService } from "@/lib/ghl-sync-service"
import { describe, it, expect, beforeAll, afterAll } from "@jest/globals"

describe("Auto-Generate All Available Fields", () => {
    const uniqueId = `JEST_TEST_ALL_FIELDS_${Date.now()}_${Math.random().toString(36).substring(7)}`
    let testSuperAdminId: string
    let createdFieldGroupId: string | null = null
    let ghlService: GHLSyncService | null = null
    let ghlCustomFieldsCount = 0

    beforeAll(async () => {
        console.log("\n=== Auto-Generate All Available Fields Test - START ===\n")

        // Create test super admin
        const testAdmin = await db.userProfile.create({
            data: {
                name: `Test Admin ${uniqueId}`,
                email: `admin-all-fields-${uniqueId}@test.com`,
                role: "super_admin" as any,
                clerkUserId: `clerk-all-fields-${uniqueId}`,
            },
        })
        testSuperAdminId = testAdmin.clerkUserId!
        console.log(`✓ Created test super admin: ${testAdmin.email}`)

        // Initialize GHL service to fetch available fields
        const settings = await db.crmSyncSettings.findFirst()
        if (settings?.ghlApiKey && settings?.ghlLocationId) {
            ghlService = new GHLSyncService(settings.ghlApiKey, settings.ghlLocationId)

            // Fetch and count custom fields
            const customFields = await ghlService.fetchCustomFields()
            ghlCustomFieldsCount = customFields.length
            console.log(`✓ GHL has ${ghlCustomFieldsCount} custom fields available`)
        }
    })

    afterAll(async () => {
        console.log("\n=== Auto-Generate All Available Fields Test - CLEANUP ===\n")

        // IMPORTANT: Do NOT delete field mappings or the field group!
        // The auto-generation creates/reuses the SYSTEM group which is shared
        // across the app. Deleting it would break GHL sync for real users.
        // 
        // We only clean up test-specific data (test users).
        if (createdFieldGroupId) {
            console.log(`ℹ️ Preserving field group ${createdFieldGroupId} and its mappings (shared system resource)`)
        }

        // Delete test super admin only
        await db.userProfile.deleteMany({
            where: {
                AND: [
                    { email: { contains: 'JEST_TEST_' } },
                    { email: { contains: uniqueId } },
                    { email: { endsWith: '@test.com' } }
                ]
            }
        })
        console.log(`✓ Deleted test users`)

        await db.$disconnect()
    })

    it("Should auto-generate mappings for MORE than 10 fields", async () => {
        // ARRANGE: Setup auto-generation service
        const settings = await db.crmSyncSettings.findFirst()
        expect(settings).toBeDefined()
        expect(settings?.ghlApiKey).toBeDefined()
        expect(settings?.ghlLocationId).toBeDefined()

        const autoGenService = new AutoGenerationService(
            settings!.ghlApiKey!,
            settings!.ghlLocationId!
        )

        // ACT: Run auto-generation
        const result = await autoGenService.autoGenerateMappings(testSuperAdminId)

        // Store group ID for cleanup
        if (result.groupId) {
            createdFieldGroupId = result.groupId
        }

        // ASSERT: Should succeed
        expect(result.success).toBe(true)
        console.log(`\nAuto-generation result:`)
        console.log(`- Mappings created: ${result.mappingsCreated}`)
        console.log(`- Mappings skipped: ${result.mappingsSkipped}`)
        console.log(`- Total attempted: ${result.mappingsTotal}`)

        // ASSERT: Should create more than 10 mappings
        expect(result.mappingsTotal).toBeGreaterThan(10)
        expect(result.mappingsCreated + result.mappingsSkipped).toBe(result.mappingsTotal)

        // ASSERT: Verify mappings exist in database
        const allMappings = await db.fieldMapping.findMany({
            where: {
                groupId: createdFieldGroupId!,
                isAutoGenerated: true
            },
            include: {
                appField: true,
                ghlField: true
            }
        })

        console.log(`\nVerification:`)
        console.log(`- Mappings in database: ${allMappings.length}`)
        expect(allMappings.length).toBeGreaterThan(10)

        // ASSERT: Verify mapping details
        let standardFieldMappings = 0
        let customFieldMappings = 0

        for (const mapping of allMappings) {
            if (mapping.ghlField.isSystemField) {
                standardFieldMappings++
            } else {
                customFieldMappings++
            }

            // Every mapping should have sync direction set
            expect(mapping.syncDirection).toBe("app_to_ghl")
            expect(mapping.isEnabled).toBe(true)
            expect(mapping.isAutoGenerated).toBe(true)
        }

        console.log(`- Standard field mappings: ${standardFieldMappings}`)
        console.log(`- Custom field mappings: ${customFieldMappings}`)

        // Standard fields should be present (at minimum: email, firstName, lastName, phone, name, companyName, website)
        expect(standardFieldMappings).toBeGreaterThanOrEqual(7)

        // Should have custom field mappings if custom fields exist in GHL
        if (ghlCustomFieldsCount > 0) {
            console.log(`Note: ${ghlCustomFieldsCount} GHL custom fields available`)
        }
    })

    it("Should include website field mapping for employer", async () => {
        // ARRANGE: Setup auto-generation service
        const settings = await db.crmSyncSettings.findFirst()
        const autoGenService = new AutoGenerationService(
            settings!.ghlApiKey!,
            settings!.ghlLocationId!
        )

        // ACT: Run auto-generation
        const result = await autoGenService.autoGenerateMappings(testSuperAdminId)
        if (result.groupId) {
            createdFieldGroupId = result.groupId
        }

        // ASSERT: Find website mapping
        const websiteMapping = await db.fieldMapping.findFirst({
            where: {
                groupId: createdFieldGroupId!,
                appField: {
                    fieldKey: "Employer.companyWebsite"
                }
            },
            include: {
                appField: true,
                ghlField: true
            }
        })

        console.log(`\nWebsite mapping:`)
        if (websiteMapping) {
            console.log(`✓ Found: ${websiteMapping.appField.fieldKey} → ${websiteMapping.ghlField.ghlFieldKey}`)
            expect(websiteMapping).toBeDefined()
            expect(websiteMapping?.ghlField.ghlFieldKey).toBe("website")
        } else {
            console.log(`✗ Website mapping NOT found - may need to add to auto-generation`)
        }
    })

    it("Should skip duplicate mappings on second run", async () => {
        // ARRANGE: Run auto-generation once
        const settings = await db.crmSyncSettings.findFirst()
        const autoGenService = new AutoGenerationService(
            settings!.ghlApiKey!,
            settings!.ghlLocationId!
        )

        const firstRun = await autoGenService.autoGenerateMappings(testSuperAdminId)
        if (firstRun.groupId) {
            createdFieldGroupId = firstRun.groupId
        }

        const firstRunCount = firstRun.mappingsCreated

        // ACT: Run auto-generation again with same user
        const secondRun = await autoGenService.autoGenerateMappings(testSuperAdminId)

        // ASSERT: Second run should skip all existing mappings
        console.log(`\nSecond run:`)
        console.log(`- First run created: ${firstRunCount}`)
        console.log(`- Second run skipped: ${secondRun.mappingsSkipped}`)
        console.log(`- Second run created: ${secondRun.mappingsCreated}`)

        expect(secondRun.mappingsCreated).toBe(0)
        expect(secondRun.mappingsSkipped).toBeGreaterThan(0)
    })
})
